### ISSUE TITLE
哥，更新下数据库啊。

### ISSUE THREAD

**Issue by skywind3000** [asins/vim-dict#4]
咱们这个仓库里，c的词典，只有 100 多个单词，

你看下面这个，1500多个单词。

https://github.com/jayli/vim-dictionary/blob/master/dict/c.dict

咱们 python 的词典只有 200 个单词，那个库有 800 多个单词。

另外能不能给 txt/markdown 之类的文本增加一个 google 的 10000 个最常用英文单词：

https://github.com/neoclide/coc-sources/blob/master/packages/word/10k.txt

？？

**Comment by asins** [comment]
欢迎提交PR

**Comment by asins** [comment]
已经做了更新，感谢告诉更好的方案。

**Comment by skywind3000** [comment]
thanks
